# Generated by Django 2.2.5 on 2019-09-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20190929_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.CharField(max_length=5000),
        ),
    ]
