# Generated by Django 2.2.5 on 2019-10-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_auto_20191003_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='lesson.Lesson'),
        ),
    ]
