# Generated by Django 2.2.5 on 2019-10-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20191003_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
